springdoc:
  api-docs:
    path: /openapi
server:
  port: 3000

spring:
  datasource:
    # H2 file
    url: jdbc:h2:file:./db/nnw
  jpa:
    show-sql: true
    properties:
      ## Hibernate Properties
      # The SQL dialect makes Hibernate generate better SQL for the chosen database
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

    # Hibernate ddl auto (create, create-drop, validate, update)
    hibernate:
      ddl-auto: update